### ISSUE TITLE
Post route not working

### ISSUE THREAD

**Issue by AlexJBustillos** [AlexJBustillos/Loud-and-Green#1]
I have a form in my strainIndex.ejs page but my post is not working
![Screen Shot 2020-12-02 at 4 54 47 PM](https://user-images.githubusercontent.com/70779389/100936168-1c1d1d00-34bf-11eb-98cf-807c630fe664.png)

``` js
router.post('/:name', isLoggedIn, (req, res) => {
    db.strain.findOrCreate({
        where: {
            strainId: req.body.strainId
        }
    }).then((foundStrain) => {
        db.user.findOne({
            where: {
                id: req.body.id
            }
        }).then((id) => {
            id.addStrain(foundStrain)
        })
    }).catch(err => {
        console.log(err);
    })
    res.redirect('strains/strainIndex')

});
```

**Comment by romebell** [comment]
Whenever you make this post are you logged in? Also, your action on this [line](https://github.com/AlexJBustillos/Loud-and-Green/blob/7154628623c7cc1a4a5d036e24b7ec7189743b63/views/strains/strainIndex.ejs#L10) is going to `controllers/users`

**Comment by AlexJBustillos** [comment]
Yeah I'm logged in, I had the action as controllers/users cus that's where the post route is. I get a little confused with the action value, is it supposed to be going to another controller?

**Comment by AlexJBustillos** [comment]
```js
router.post('/', isLoggedIn, (req, res) => {
    db.strain.findOrCreate({
        where: {
            strainId: req.body.strainId
        }
    }).then((foundStrain) => {
        db.user.findOne({
            where: {
                email: req.body.email,
                id: req.user.id
            }
        }).then((user) => {
            user.addStrain(foundStrain)
        })
    }).catch(err => {
        console.log(err);
    })
    res.redirect('/profile')

});
```
